Actions
openmicroscopy/bio-formats-octave-docker pull request #36
Opened 2020-12-05 21:43 UTC by jburel

Replace travis by GHA

cc @sbesson

2020-12-06 08:36 UTC, jburel commented
see https://github.com/jburel/bio-formats-octave-docker/actions/runs/403071520

2020-12-07 17:04 UTC, sbesson requested changes
A few suggestions/comments.

Independent of the changes proposing in PR, while reviewing the various Docker repositories and the migration to GitHub actions, I feel there might be an opportunity to rationalize/automate the  Docker images release workflow (currently based on `Makefile` copied in various repos). I suppose you don't have anything staging that would achieve this functionality? /cc @joshmoore

2020-12-07 17:04 UTC, sbesson commented on .github/workflows/main.yml
> +          if [ ! -f data/tubhiswt-2D/tubhiswt_C0.ome.tif ]; then wget --user-agent GHA https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/tubhiswt-2D.zip && unzip tubhiswt-2D.zip && mv tubh
The first conditional only makes sense if we introduce some caching for the downloaded data.

2020-12-07 17:04 UTC, sbesson commented on .github/workflows/main.yml
> +      - name: Test
Maybe separate the step downloading/creating the sample data from the step running the tests?

2020-12-07 17:04 UTC, sbesson commented on README.md
> -[![Build Status](https://travis-ci.org/openmicroscopy/bio-formats-octave-docker.svg)](https://travis-ci.org/openmicroscopy/bio-formats-octave-docker)
Need updating to point at the actions

2020-12-07 17:04 UTC, sbesson commented on .github/workflows/main.yml
> +          docker run -t -v $(pwd)/data/:/data/ bio-formats-octave ci_test.m /data/tubhiswt-2D/tubhiswt_C0.ome.tif
The renaming of the file to drop Travis makes sense. Maybe it should even be simply `test.m` (like `test.sh` in other Docker repos)

2020-12-09 09:25 UTC, sbesson commented on .github/workflows/main.yml
> +          if [ ! -f data/tubhiswt-2D/tubhiswt_C0.ome.tif ]; then wget --user-agent GHA https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/tubhiswt-2D.zip && unzip tubhiswt-2D.zip && mv tubh
```suggestion
          wget --user-agent GHA https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/tubhiswt-2D.zip && unzip tubhiswt-2D.zip && mv tubhiswt-2D data
```

assuming the caching is a next todo

2020-12-09 11:57 UTC, sbesson approved these changes

2020-12-09 11:59 UTC, sbesson commented
:+1: as my question about the release workflow was unanswered, I assume we will come back to it in a second step. Happy to see this merged immediately to continue the transition to GHA

2020-12-09 12:00 UTC, merged